### ISSUE TITLE
Gear Checks reports missing enchant on Thrown Items

### ISSUE THREAD

**Issue by Kolmarwow** [Road-block/CharacterStatsPaneImproved#3]
Gear Checks reports that ranged slot is missing an enchant if you're using a thrown item, but as far as I know there doesn't exist any enchants at all for thrown items. Could be the same for relics/wands but I don't have characters to test that.
CSP Improved version: 1.2.7

**Comment by Road-block** [comment]
Thanks I'll fix that. 
I started out with exception for all off-hands (except shield / weapon) but folks informed me there's enchants for frills.
It already excludes wands. 
I should probably exclude relics from enchant checks and I'll add thrown.

**Comment by Road-block** [comment]
I checked and I'm actually already excluding armor subtypes in ranged slot (so relics shouldn't need a change).
It's only thrown that need added to exclusions.

**Comment by Road-block** [comment]
fixed with 60367cde02746f731839307a39dbb38908c9182c
