### ISSUE TITLE
Gear Checks Back Tinker

### ISSUE THREAD

**Issue by Okumba** [Road-block/CharacterStatsPaneImproved#4]
Gear Check says I'm missing 1 Tinker for Back slot even though I have "Lightweave Embroidery" from Tailoring on it (highest version).

Game Version: Cata Classic
English Client

**Comment by Road-block** [comment]
Are you also an engineer?
Engineering tinkers stack with regular enchants.
I might have to have special handling if Tailoring enchants do not count as a regular (Enchanting) enchant and compete with Engi tinkers (ie you can only have one of the two)

**Comment by Road-block** [comment]
I confirmed with a guildie, that's tailor/engi. You can have both so addon is not wrong 😉
